server:
  port: 7050
spring:
  application:
    name: cloud-service-common
  zipkin:
    base-url: http://localhost:7411
eureka:
  client:
    service-url:
      defaultZoone: http://localhost:8761/eureka/